name: Code Quality Checks

on:
  - workflow_call

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup-node
        with:
          node-version: '20.x'

      - name: Check Formatting
        run: yarn format

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup-node
        with:
          node-version: '20.x'

      - name: Lint
        run: yarn lint
