name: ECS Deploy

on:
  workflow_call:
    inputs:
      STAGE:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy:
    name: Build and deploy
    timeout-minutes: 15
    environment: ${{ inputs.STAGE }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: >-
          AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}
          yarn ecs-deploy build backend --ci true --stage ${{ inputs.STAGE }} --release $GITHUB_SHA --verbose

      - name: Deploy
        run:  >-
          AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}
          yarn ecs-deploy deploy --ci true --stage ${{ inputs.STAGE }} --release $GITHUB_SHA --verbose
