name: Build and deploy prd

on:
  push:
    branches:
      - 'myapp-dev'

jobs:
  build-and-deploy:
    name: Build and deploy
    uses: ./.github/workflows/ecs-deploy.yml
    with:
      STAGE: myapp-dev
    secrets:
      # set these in GitHub Project Environment by the name of the STAGE
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
