name: Test End-to-End (E2E)

on:
  - workflow_call

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup-node
        with:
          node-version: '20.x'

      - name: Set up Docker Compose
        run: docker-compose -v

      - name: Start services
        run: yarn docker:ci:up

      - name: Run E2E Tests
        run: yarn test:e2e

      - name: Shutdown services
        run: yarn docker:ci:down:clear
